2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Current SDK version is 0.15.7
2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Configure stats pid to 8856
2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ferti\.config\wandb\settings
2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ferti\Documents\RL_Modular\wandb\settings
2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-31 14:45:31,705 INFO    MainThread:8856 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_deep_policy.py', 'program': 'c:\\Users\\ferti\\Documents\\RL_Modular\\train_deep_policy.py'}
2023-07-31 14:45:31,707 INFO    MainThread:8856 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\ferti\Documents\RL_Modular\wandb\run-20230731_144531-w8xcat2y\logs\debug.log
2023-07-31 14:45:31,707 INFO    MainThread:8856 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\ferti\Documents\RL_Modular\wandb\run-20230731_144531-w8xcat2y\logs\debug-internal.log
2023-07-31 14:45:31,708 INFO    MainThread:8856 [wandb_init.py:init():547] calling init triggers
2023-07-31 14:45:31,708 INFO    MainThread:8856 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-31 14:45:31,708 INFO    MainThread:8856 [wandb_init.py:init():596] starting backend
2023-07-31 14:45:31,708 INFO    MainThread:8856 [wandb_init.py:init():600] setting up manager
2023-07-31 14:45:31,720 INFO    MainThread:8856 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-07-31 14:45:31,720 INFO    MainThread:8856 [wandb_init.py:init():606] backend started and connected
2023-07-31 14:45:31,752 INFO    MainThread:8856 [wandb_init.py:init():697] updated telemetry
2023-07-31 14:45:32,052 INFO    MainThread:8856 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-07-31 14:45:33,018 ERROR   MainThread:8856 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-31 14:45:33,369 ERROR   MainThread:8856 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-31 14:45:34,388 WARNING MsgRouterThr:8856 [router.py:message_loop():77] message_loop has been closed
